//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webComponentT2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaskTable
    {
        public int TaskID { get; set; }
        public string UserEmail { get; set; }
        [Required]
        public string NotiName { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public string TimeTask { get; set; }
    }
}
